#!/bin/bash
# Test runner for gptel-workflow

echo "=== gptel-workflow Test Suite ==="
echo ""
echo "Note: This environment does not have Emacs installed."
echo "To run the full ERT test suite, execute:"
echo ""
echo "  emacs --batch -L . -l tests/gptel-workflow-test.el -f ert-run-tests-batch-and-exit"
echo ""
echo "Available test files:"
ls -lh tests/gptel-workflow-test.el
echo ""
echo "Workflow implementation files:"
ls -lh gptel-workflow*.el
echo ""
echo "To use the workflow in Emacs:"
echo "1. Load the modules: (require 'gptel-workflow) (require 'gptel-workflow-transient)"
echo "2. Start workflow: M-x gptel-workflow-menu"
echo "3. Or use programmatically: (gptel-workflow-start 'region '(\"AC1\") nil)"
echo ""
echo "=== Test Structure ==="
echo "- State management tests"
echo "- AC tagging and extraction tests"
echo "- Context pruning tests"
echo "- Validation gate tests (plan, diff, tests, review)"
echo "- Prompt building tests"
echo "- State progression tests"
echo "- Retry tests"
echo "- Integration test flag tests"
echo "- Output formatting tests"
echo "- Logging tests"
echo "- Preset configuration tests"
echo "- Edge case tests"
echo ""
echo "=== Manual Testing Guide ==="
echo "1. Open Emacs with gptel configured"
echo "2. Load workflow: (require 'gptel-workflow-transient)"
echo "3. Select a region in a buffer"
echo "4. Run: M-x gptel-workflow-menu"
echo "5. Configure options and start workflow"
echo "6. Use per-step menu to proceed/retry/edit"
